#!/bin/bash

upgrade_ov() {
  UPGRADE_SCRIPT_URL="https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/install_openvidu_OVVERSION.sh"
  HTTP_STATUS=$(curl -s -o /dev/null -I -w "%{http_code}" ${UPGRADE_SCRIPT_URL//OVVERSION/$1})

  printf "  => Upgrading Openvidu CE to %s Version" "$1"

  if [ "$HTTP_STATUS" == "200" ]; then
    printf "\n    => Downloading new Version"
    printf "\n"
    curl ${UPGRADE_SCRIPT_URL//OVVERSION/$1} | bash -s upgrade
  else
     printf "\n     =======¡ERROR!======="
     printf "\n     Openvidu CE Version %s not exist" "$1"
     printf "\n"
     exit 0
  fi
}

usage() {
    printf "Usage: \n\t openvidu [command]"
    printf "\n\nAvailable Commands:"
    printf "\n\tstart\t\t\tStart all services"
    printf "\n\tstop\t\t\tStop all services"
    printf "\n\trestart\t\t\tRestart all stoped and running services"
    printf "\n\tlogs\t\t\tShow openvidu-server logs"
    printf "\n\tupgrade\t\t\tUpgrade to the lastest Openvidu version"
    printf "\n\tupgrade [version]\tUpgrade to the specific Openvidu version"
    printf "\n\thelp\t\t\tShow help for openvidu command"
    printf "\n"
}

case $1 in

  start)
    docker-compose up -d
    docker-compose logs -f openvidu-server
    ;;

  stop)
    docker-compose down
    ;;

  restart)
    docker-compose down
    docker-compose up -d
    docker-compose logs -f openvidu-server
    ;;

  logs)
    docker-compose logs -f openvidu-server
    ;;

  upgrade)
    if [ -z "$2" ]; then
      upgrade_ov latest
    else
      upgrade_ov "$2"
    fi
    ;;
  upgrade-restart)
    OLD_OPENVIDU_FOLDER=$(ls -tda .old* | head -1)

    if [ ! -z ${OLD_OPENVIDU_FOLDER} ]; then
      docker-compose -f "${OLD_OPENVIDU_FOLDER}/docker-compose.yml" down
      docker-compose up -d
      docker-compose logs -f openvidu-server
    else
      printf "\n     =======¡ERROR!======="
      printf "\n     There are no Openvidu CE previous updates"
      printf "\n"
      exit 0
    fi
    ;;
  *)
    usage
    ;;
esac
