export enum ArchiveLayout {
    BEST_FIT = 'BEST_FIT',
    PICTURE_IN_PICTURE = 'PICTURE_IN_PICTURE',
    VERTICAL_PRESENTATION = 'VERTICAL_PRESENTATION',
    HORIZONTAL_PRESENTATION = 'VERTICAL_PRESENTATION'
}
