/**
 * Defines property [[OpenViduError.name]]
 */
export declare enum OpenViduErrorName {
    BROWSER_NOT_SUPPORTED = "BROWSER_NOT_SUPPORTED",
    CAMERA_ACCESS_DENIED = "CAMERA_ACCESS_DENIED",
    MICROPHONE_ACCESS_DENIED = "MICROPHONE_ACCESS_DENIED",
    SCREEN_CAPTURE_DENIED = "SCREEN_CAPTURE_DENIED",
    SCREEN_SHARING_NOT_SUPPORTED = "SCREEN_SHARING_NOT_SUPPORTED",
    SCREEN_EXTENSION_NOT_INSTALLED = "SCREEN_EXTENSION_NOT_INSTALLED",
    SCREEN_EXTENSION_DISABLED = "SCREEN_EXTENSION_DISABLED",
    INPUT_VIDEO_DEVICE_NOT_FOUND = "INPUT_VIDEO_DEVICE_NOT_FOUND",
    INPUT_AUDIO_DEVICE_NOT_FOUND = "INPUT_AUDIO_DEVICE_NOT_FOUND",
    NO_INPUT_SOURCE_SET = "NO_INPUT_SOURCE_SET",
    PUBLISHER_PROPERTIES_ERROR = "PUBLISHER_PROPERTIES_ERROR",
    OPENVIDU_PERMISSION_DENIED = "OPENVIDU_PERMISSION_DENIED",
    OPENVIDU_NOT_CONNECTED = "OPENVIDU_NOT_CONNECTED",
    GENERIC_ERROR = "GENERIC_ERROR",
}
/**
 * Simple object to identify runtime errors on the client side
 */
export declare class OpenViduError {
    name: OpenViduErrorName;
    message: string;
    /**
     * @hidden
     */
    constructor(name: OpenViduErrorName, message: string);
}
